### ISSUE TITLE
Add StandardFirmataWifi

### ISSUE THREAD

**Issue by d1runberg** [johnny-five-io/nodebots-interchange#21]
Add StandardFirmata Wifi and then UI options for setting IP address and Port #, SSID and password. Would be awesome for using the ESP8266 (and possibly the ESP32) with J5 without having to upload code from Arduino.

**Comment by ajfisher** [comment]
At the moment this won't work with Interchange because the flashing
component of this uses a specific tool for the ESP*. There is a plan to
make this work but it means porting the flashing tool (currently in python)
to JS so it can run within interchange. It's on the list - but there's a
fair amount of time required to bake this in.

In addition, because you need a mechanism to supply credentials etc it will
mean extending the capability of Interchange to be able to supply all of
this and pass it in over serial post-flash (the way the I2C setting s tuff
works).

My current view on this is that given ESP* devices are not aimed at novice
NodeBoticists, you're at a point where having the Arduino IDE or other
toolchains installed is highly likely anyway and the utility of Interchange
in this context is quite reduced.

It's definitely on the roadmap and will make an appearance but I'd like to
see wider backpack support first at this point (unless someone was prepared
to take this on and build it - PRs gratefully received)...

**Comment by d1runberg** [comment]
Makes sense! I know the esps are wonky. I get your point about the goals of interchange for beginners and more advanced users would already have arduino installed...I'm just being lazy and never want to open arduino

**Comment by ajfisher** [comment]
HA HA! I hear that - I try to avoid it when I can as well. Definitely in the roadmap so I'll allocate this to there.

**Comment by frxnz** [comment]
I just want to second never wanting to open the Arduino IDE

**Comment by ajfisher** [comment]
Closing this off due to the quirks associated with this and needing to port estool.py to interchange to make this even remotely work.
